insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('The 21 Carat Snatch', 5.8, 33, 9);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Scandal', 28.79, 40, 2);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Lollilove', 16.19, 17, 8);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Masks (Masques)', 19.22, 41, 4);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Lost Christmas', 25.46, 37, 6);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Thing from Another World, The', 9.54, 27, 4);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Champagne', 7.15, 21, 5);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('That Was Then... This Is Now', 16.54, 41, 4);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Cousin Angelica (La prima Angélica)', 16.0, 9, 8);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Level Five', 21.11, 48, 9);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Angele', 13.72, 19, 1);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Varg Veum - Bitter Flowers (Varg Veum - Bitre Blomster)', 26.96, 21, 12);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Commare secca, La (Grim Reaper, The)', 19.61, 24, 7);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Wild Card', 20.39, 19, 5);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Brothers Rico, The', 10.09, 44, 9);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Dallas 362', 5.69, 44, 2);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('American Tail: Fievel Goes West, An', 7.71, 11, 6);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Still Mine', 9.27, 28, 1);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Personals, The (Zheng hun qi shi)', 19.05, 4, 12);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Ten Thousand Saints', 14.59, 11, 10);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Brothers Bloom, The', 10.01, 17, 11);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Straight from the Heart', 18.73, 33, 6);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Down Periscope', 11.44, 32, 14);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Memories (Memorîzu)', 9.88, 18, 2);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Sorority Boys', 12.66, 35, 7);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Turtle Diary', 10.97, 34, 10);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Labor Day', 7.36, 39, 7);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Gus', 6.71, 14, 9);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Bluebeard', 20.21, 32, 9);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Head Over Heels', 26.69, 35, 3);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Prisoners', 15.31, 14, 12);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Free Samples', 17.62, 5, 2);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Little Fauss and Big Halsy', 24.12, 15, 6);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Pulse (Kairo)', 27.3, 12, 6);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Heaven', 24.25, 39, 10);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Julius Caesar', 18.46, 36, 8);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Rebirth of Mothra III', 23.11, 33, 5);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Boogeyman', 14.61, 7, 7);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Good Morning, Night (Buongiorno, notte)', 16.4, 19, 7);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Grudge, The', 25.75, 40, 6);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('That Certain Summer', 29.49, 21, 12);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Man Who Would Be King, The', 17.56, 23, 6);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Knockin'' on Heaven''s Door', 21.67, 42, 10);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Christmas on Mars', 21.65, 22, 5);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Jesse James', 21.23, 47, 8);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Madison', 24.34, 7, 6);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Legally Blondes', 21.43, 34, 1);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Monty Python: Almost the Truth - Lawyers Cut', 22.34, 15, 4);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Dead Ringers', 29.62, 13, 4);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Grocer''s Son, The (Fils de l''épicier, Le)', 25.6, 7, 6);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Love Story 2050', 20.76, 33, 8);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('NATO''s Secret Armies (Gladio: L''esercito segreto della Nato)', 17.39, 2, 11);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Life and Times of Judge Roy Bean, The', 13.24, 43, 9);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('What Price Glory', 21.62, 40, 8);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Confidentially Yours (Vivement dimanche!)', 9.16, 9, 9);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Radio On', 27.49, 44, 3);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Everybody Wants to Be Italian', 23.33, 41, 7);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Accused (Anklaget)', 12.45, 39, 8);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Jim Jefferies: Alcoholocaust', 5.77, 49, 7);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('My Way to Olympia (Mein Weg nach Olympia)', 20.45, 4, 1);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Oscar and Lucinda (a.k.a. Oscar & Lucinda)', 16.0, 47, 5);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Monster in the Closet', 22.5, 5, 9);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Burnt by the Sun (Utomlyonnye solntsem)', 23.8, 48, 2);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Frozen Fever', 15.51, 49, 13);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Purge (Puhdistus)', 26.88, 43, 8);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Making a Killing: The Untold Story of Psychotropic Drugging', 26.93, 41, 1);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Hellboy II: The Golden Army', 18.48, 5, 10);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('We Are What We Are', 20.6, 20, 9);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Orphan', 26.83, 43, 8);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('When Evening Falls on Bucharest or Metabolism', 21.33, 10, 5);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('That Sinking Feeling', 7.8, 4, 5);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Confidential Agent', 23.45, 27, 6);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Deadly Advice', 14.23, 32, 12);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Unbearable Lightness of Being, The', 5.58, 48, 12);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Little Odessa', 14.31, 22, 8);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('13 Tzameti', 7.99, 38, 1);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('In A Day', 7.73, 28, 14);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Never Say Never Again', 26.35, 23, 3);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('John Q', 12.18, 30, 3);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Kai Po Che!', 14.79, 1, 2);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Virtuosity', 9.3, 31, 7);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Story of Film: An Odyssey, The', 22.22, 12, 8);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Sunshine State', 8.51, 26, 6);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Butcher, The (Boucher, Le)', 8.85, 44, 13);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Gridlock''d', 26.12, 25, 4);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Transistor Love Story (Monrak Transistor)', 5.1, 29, 2);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Foolish Wives', 18.19, 37, 3);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Sentinel, The', 21.92, 23, 9);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Do You Wanna Know a Secret?', 8.96, 17, 14);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Gate of Hell (Jigokumon)', 26.71, 36, 3);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Juggernaut', 25.58, 34, 5);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Three Guys Named Mike', 11.31, 25, 11);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Endurance: Shackleton''s Legendary Antarctic Expedition, The', 24.2, 40, 2);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Delhi-6', 24.19, 7, 11);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Magic Flute, The (Trollflöjten)', 22.95, 28, 2);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Chocchan''s Story (Chocchan monogatari)', 25.72, 20, 2);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('I Will Follow You Into the Dark', 5.18, 25, 10);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Submarino', 11.55, 11, 3);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Killer McCoy', 9.62, 43, 2);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Circus', 5.31, 36, 8);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Rutles 2: Can''t Buy Me Lunch, The', 6.79, 50, 7);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Joe''s Apartment', 23.79, 2, 5);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Mysterious Object at Noon (Dokfa nai meuman)', 24.51, 36, 13);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Suzanne''s Career (La carrière de Suzanne)', 21.59, 44, 6);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Line of Sight', 22.08, 16, 10);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Sleeping Dictionary, The', 19.04, 8, 7);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Appointment with Death', 26.61, 6, 14);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Lake Placid', 28.83, 31, 2);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Lavender Hill Mob, The', 8.99, 16, 1);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('The Blue Room', 25.95, 42, 6);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Run Ronnie Run', 5.8, 42, 5);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Few Best Men, A', 17.78, 39, 5);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Girl Next Door, The', 5.4, 49, 10);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Wyrmwood', 17.2, 32, 1);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Cruel Story of Youth (Seishun zankoku monogatari)', 15.02, 23, 8);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Sword and the Sorcerer, The', 11.25, 11, 7);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Keane', 11.3, 5, 13);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Boxcar Bertha', 27.19, 28, 13);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Darkon', 15.27, 30, 11);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Stretch', 8.48, 1, 10);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Wrestling Queens', 26.28, 32, 7);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Valhalla', 8.66, 28, 10);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Hamlet', 5.84, 40, 11);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Never a Dull Moment', 18.46, 22, 13);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Movie Days (Bíódagar)', 6.05, 25, 11);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Opposite of Sex, The', 23.25, 35, 14);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Sign of Leo, The (Signe du lion, Le)', 23.14, 21, 8);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Sleepaway Camp', 27.36, 46, 6);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Storm Center', 26.92, 31, 14);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('April Captains (Capitães de Abril)', 29.28, 44, 14);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Creepshow 3', 25.55, 11, 10);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Zach Galifianakis: Live at the Purple Onion', 18.74, 32, 12);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Hell''s Hinges', 6.23, 2, 9);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Nice Guy Johnny', 7.21, 41, 8);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('El Cid', 21.29, 36, 5);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Party, The (Boum, La)', 29.16, 8, 9);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Downhill', 8.09, 32, 4);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Unforgotten: Twenty-Five Years After Willowbrook', 16.38, 8, 5);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Kiss the Bride', 12.22, 10, 6);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Adventures of Ichabod and Mr. Toad, The', 8.28, 37, 12);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Dil Se', 7.84, 41, 12);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('From B Movie to Cult Film: Western', 17.12, 36, 2);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Van Diemen''s Land', 20.04, 1, 10);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('How to Draw a Bunny', 24.85, 14, 13);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Mysteries of Pittsburgh, The', 24.45, 47, 3);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Triangle (Tie saam gok)', 11.16, 2, 8);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Chimpanzee', 5.01, 41, 13);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Closer', 13.42, 42, 2);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Leningrad Cowboys Go America', 12.55, 40, 9);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Little Traitor, The', 8.18, 47, 1);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Christiane F. (a.k.a. We Children from Bahnhof Zoo) (Christiane F. - Wir Kinder vom Bahnhof Zoo)', 5.34, 30, 14);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Hurricane, The', 29.38, 1, 5);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Beast from Haunted Cave', 8.24, 14, 7);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Earth Trembles, The (Terra trema: Episodio del mare, La)', 26.49, 12, 14);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('X-Men Origins: Wolverine', 26.48, 4, 1);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Greatest, The', 23.78, 41, 1);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Tropico', 14.9, 38, 3);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Raven, The', 10.47, 45, 10);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Glorious Technicolor', 9.55, 2, 4);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Badmaash Company', 18.33, 34, 7);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Bullets Over Broadway', 11.59, 45, 9);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Lotte Reiniger: Homage to the Inventor of the Silhouette Film', 13.04, 45, 5);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Children of Nature (Börn náttúrunnar)', 19.67, 20, 6);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('The Last Journey', 6.12, 32, 7);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Samsara', 14.05, 24, 7);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Rugrats Movie, The', 14.42, 22, 1);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Sunshine Boys, The', 25.49, 22, 7);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Abbott and Costello Go to Mars', 5.11, 35, 2);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Paradise Road', 23.05, 26, 8);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Naked Blood: Megyaku (Nekeddo burâddo: Megyaku)', 15.33, 17, 11);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Masks (Masques)', 12.03, 32, 12);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Best Exotic Marigold Hotel, The', 19.72, 17, 7);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Star Kid', 23.42, 11, 1);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Centennial', 10.49, 39, 4);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Battle Royale 2: Requiem (Batoru rowaiaru II: Chinkonka)', 24.64, 46, 1);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Voodoo Tiger', 19.92, 5, 13);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Always', 5.99, 11, 12);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Banklady', 20.02, 18, 14);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Boots and Saddles', 9.89, 2, 4);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Sweeney Todd: The Demon Barber of Fleet Street', 23.28, 8, 11);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('ATF ', 11.97, 20, 13);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Scandali nudi', 6.09, 33, 11);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Yu-Gi-Oh!', 5.59, 8, 12);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Love Movie, The (Rakkauselokuva)', 5.45, 30, 9);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Hear No Evil', 27.5, 25, 10);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Hardware', 12.06, 27, 4);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Tell It to the Marines', 11.34, 2, 1);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('One False Move', 18.42, 6, 10);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Brief Vacation, A (breve vacanza, Una)', 19.95, 48, 4);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Fantastic Flesh: The Art of Make-Up EFX', 24.04, 47, 14);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Night and the City', 6.47, 19, 2);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Dragon Crusaders', 20.15, 35, 9);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Eden Log', 29.95, 15, 12);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Whip It', 15.79, 7, 3);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Toast of New Orleans, The', 26.03, 10, 14);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Evil Bong', 27.01, 30, 6);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('That Obscure Object of Desire (Cet obscur objet du désir)', 10.07, 12, 7);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Utopia', 20.4, 19, 4);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Death to Smoochy', 16.9, 46, 1);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Vivien Leigh: Scarlett and Beyond', 7.16, 20, 6);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Nice Guy Johnny', 24.87, 35, 2);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Short Time', 23.63, 43, 11);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Out of Mind: The Stories of H.P. Lovecraft', 23.44, 36, 5);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Hound of the Baskervilles, The', 11.06, 50, 6);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Random Harvest', 7.56, 38, 3);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('The Raid 2: Berandal', 20.95, 9, 5);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Great Gabbo, The', 13.72, 23, 8);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Island of Lost Souls', 29.17, 15, 12);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('My Cousin Vinny', 14.95, 1, 12);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Exhibition', 23.24, 1, 12);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Liliom', 24.27, 6, 4);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Nightbreed', 19.9, 41, 3);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Daybreak', 22.81, 42, 10);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Vibes', 11.21, 6, 10);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Death of a Bureaucrat (La muerte de un burócrata)', 13.78, 11, 1);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Gypsy', 16.95, 9, 4);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('And the Ship Sails On (E la nave va)', 21.57, 22, 4);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Dirty Filthy Love', 21.73, 34, 3);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Badding', 9.49, 43, 11);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Quatsch und die Nasenbärbande', 28.31, 19, 6);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Silence, The (Tystnaden)', 28.1, 25, 1);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('High and Dizzy', 20.33, 30, 3);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Rookie, The', 27.39, 46, 11);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Sunrise: A Song of Two Humans', 7.69, 34, 9);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('XXY', 13.31, 8, 8);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Unforgotten: Twenty-Five Years After Willowbrook', 20.38, 12, 5);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Codependent Lesbian Space Alien Seeks Same', 29.1, 40, 13);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('CBGB', 23.45, 5, 10);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Timerider: The Adventure of Lyle Swann', 13.61, 24, 8);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Beauty in Trouble (Kráska v nesnázích)', 17.68, 18, 5);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Company Man', 25.07, 36, 12);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Paris, I Love You (Paris, je t''aime)', 24.54, 26, 14);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Year of the Gun', 7.44, 18, 4);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('George Harrison: Living in the Material World', 28.52, 19, 4);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Retrogade', 18.28, 50, 10);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Halfmoon (Paul Bowles - Halbmond)', 11.06, 33, 13);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Valkyrie', 7.99, 12, 6);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Thieves (Voleurs, Les)', 22.04, 33, 7);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Diplomatic Siege', 21.98, 26, 7);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Delirious', 24.41, 6, 3);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Puppet Master III: Toulon''s Revenge', 21.43, 11, 13);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Chances Are', 8.2, 50, 10);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Playing God', 6.7, 48, 1);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Rogue Trader', 13.88, 34, 10);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Whitecoats', 14.71, 29, 6);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Dick', 18.69, 5, 9);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Deliverance', 24.0, 32, 10);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Otis', 6.81, 36, 14);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Cabin Fever 2: Spring Fever', 16.21, 18, 12);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Vampir (Cuadecuc, vampir)', 25.26, 24, 8);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Midsummer Night''s Party, A (Midsummer of Love, A) (Sommaren med Göran)', 28.1, 1, 8);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Crackerjack', 24.53, 12, 7);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Bullet to the Head', 8.89, 35, 8);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Hellsinki (Rööperi)', 27.05, 41, 11);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Benji the Hunted', 22.77, 5, 14);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Sport, Sport, Sport', 25.83, 35, 4);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Problem Child', 24.29, 50, 12);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('On a marché sur Bangkok', 25.57, 34, 7);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Footprints on the Moon (Le orme) (Primal Impulse)', 5.75, 50, 4);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Babylon 5: The River of Souls', 9.39, 35, 5);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Adventures of Felix, The (a.k.a. Funny Felix) (Drôle de Félix)', 26.89, 11, 10);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Panda! Go Panda! Rainy Day Circus', 26.78, 19, 4);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Sleeping Beauty, The (La belle endormie)', 7.0, 38, 3);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Rent-A-Cop', 12.49, 8, 7);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Fury', 10.26, 3, 14);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Deception', 26.45, 47, 9);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Slingshot Hip Hop', 7.18, 7, 4);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Diggstown', 6.54, 44, 4);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Teenage Caveman', 5.85, 45, 10);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Beekeeper, The (O melissokomos)', 5.55, 47, 3);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Enter the Phoenix (Da lao ai mei li)', 6.03, 34, 12);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Berserk', 8.66, 36, 3);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Hotte in Paradise (Hotte im Paradies)', 19.67, 8, 10);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Star Trek: The Motion Picture', 16.25, 18, 4);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Net 2.0, The ', 10.04, 50, 11);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Beau Serge, Le', 5.74, 18, 2);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Point of Order', 11.23, 9, 2);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Thief', 11.73, 30, 1);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Santa Claus Has Blue Eyes (Le père Noël a les yeux bleus)', 16.84, 50, 2);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Onechanbara - Zombie Bikini Squad (a.k.a. Oneechanbara: The Movie)', 27.75, 37, 8);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Mother and the Whore, The (Maman et la putain, La)', 6.66, 22, 14);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Sarah Silverman: Jesus Is Magic', 19.22, 45, 3);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('My Girl 2', 25.71, 16, 1);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Champion, The', 9.08, 3, 13);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Complete History of My Sexual Failures, A', 23.91, 1, 3);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Mickey, Donald, Goofy: The Three Musketeers', 9.49, 46, 3);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Football Factory, The', 11.95, 45, 12);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Just Like Brothers (Comme des frères)', 19.97, 17, 3);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Detropia', 28.21, 6, 14);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Earrings of Madame de..., The (Madame de...)', 20.77, 6, 11);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Advise and Consent', 26.9, 49, 3);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Bye Bye Brazil (Bye Bye Brasil)', 25.91, 44, 13);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Before the Rains', 22.43, 10, 11);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Ninja: Shadow of a Tear', 15.82, 5, 5);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('And Life Goes On (a.k.a. Life and Nothing More) (Zendegi va digar hich)', 18.25, 48, 11);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('West of Zanzibar', 25.64, 14, 11);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Trial and Error', 14.73, 33, 10);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Exploding Girl, The', 10.15, 39, 11);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Secret Life of Zoey, The', 15.98, 47, 4);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Highway Racer', 5.5, 1, 6);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Nicht mein Tag', 14.44, 8, 8);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('The Bride Wore Red', 28.39, 19, 5);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Poker House, The', 5.02, 1, 3);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Visiting Hours', 25.89, 29, 6);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Geographer Drank His Globe Away, The (Geograf globus propil)', 19.45, 22, 10);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Telstar: The Joe Meek Story', 12.47, 11, 1);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Eddie', 6.29, 29, 14);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Watching the Detectives', 29.03, 7, 3);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Sword in the Stone, The', 20.33, 3, 8);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('WolfCop', 21.19, 24, 5);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Floating', 17.47, 48, 1);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Nico and Dani (Krámpack)', 24.53, 3, 7);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Fire on the Mountain', 20.68, 26, 7);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Can-Can', 15.92, 29, 12);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('4', 26.43, 28, 7);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Big Lift, The', 22.85, 5, 1);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Escape from Dartmoor', 22.09, 42, 14);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Young Tom Edison', 13.24, 50, 3);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Dangerous Method, A', 9.52, 5, 8);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Wing and a Prayer', 5.2, 35, 1);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Mommy', 20.8, 15, 7);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('No God, No Master', 16.33, 29, 9);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Welcome to the Jungle', 5.01, 32, 3);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Basquiat', 19.82, 31, 7);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Toi et Moi', 6.7, 43, 4);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Confessions of a Driving Instructor', 19.34, 24, 4);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Informant', 12.0, 50, 12);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('You''re Telling Me!', 9.43, 38, 1);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Twelfth Night', 29.54, 4, 7);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Repeaters ', 29.82, 10, 11);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Napoleon Dynamite', 8.1, 9, 11);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('American Roulette', 29.92, 40, 2);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Voodoo Dawn', 8.53, 18, 1);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Felidae', 28.67, 45, 11);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Anthony Zimmer', 13.54, 48, 3);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Popcorn', 23.1, 22, 6);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Pleasure at Her Majesty''s', 22.72, 47, 9);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('The Gilded Cage', 13.44, 49, 5);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('But I''m a Cheerleader', 17.82, 44, 4);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('What Happens in Vegas...', 5.4, 28, 8);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Delicate Delinquent, The', 19.07, 40, 8);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Rollercoaster', 9.13, 30, 12);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Nobody Will Speak of Us When We''re Dead (Nadie hablará de nosotras cuando hayamos muerto)', 8.26, 22, 1);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Hatchet III', 27.12, 17, 2);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Unfinished Piece for a Player Piano, An (Neokonchennaya pyesa dlya mekhanicheskogo pianino)', 8.55, 1, 13);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Orgazmo', 7.52, 39, 14);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('This Movie Is Broken', 13.05, 34, 4);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Manolito Four Eyes', 25.09, 40, 13);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('King of Jazz', 29.09, 36, 12);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Siberia', 15.68, 49, 7);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Fires on the Plain (Nobi)', 17.73, 29, 3);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Anna Madelina (Ngon na ma dak lin na)', 24.44, 25, 10);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Raven, The', 11.02, 16, 5);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Harvest Month, The (Elokuu)', 29.88, 8, 4);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Pistol Whipped', 19.53, 47, 1);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Little Engine That Could, The', 29.5, 28, 1);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Black Sheep (Schwarze Schafe)', 7.8, 12, 13);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Double Harness', 21.94, 37, 8);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Zatoichi in Desperation (Shin Zatôichi monogatari: Oreta tsue) (Zatôichi 24)', 11.33, 7, 6);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Pretty Bird', 24.15, 50, 12);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Poison', 6.89, 29, 4);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Love the Beast', 17.71, 26, 10);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Super', 8.08, 44, 13);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Pendulum', 6.5, 18, 9);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Heathers', 15.11, 13, 9);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('No Such Thing', 13.11, 19, 9);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Don''t Be Afraid of the Dark', 28.38, 26, 10);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('The Diary of Preston Plummer', 26.65, 38, 10);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Mission: Impossible III', 24.61, 48, 5);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Karlsson Brothers (Bröderna Karlsson)', 27.52, 46, 4);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Best of the Badmen', 15.47, 13, 2);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('I''ll See You in My Dreams', 22.82, 17, 12);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Young Lieutenant, The (Le petit lieutenant)', 22.02, 16, 11);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('The Crown Jewels', 26.63, 5, 6);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Road North (Tie pohjoiseen)', 5.18, 30, 12);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Election', 21.56, 20, 11);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Dogtooth (Kynodontas)', 13.43, 24, 4);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Boy Named Charlie Brown, A', 19.44, 23, 6);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Garbage Pail Kids Movie, The', 17.54, 15, 2);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('News from Home', 27.23, 42, 10);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Devil Hunter (El caníbal)', 29.48, 26, 7);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Wild China', 14.66, 13, 11);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('P2', 18.53, 35, 1);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Beautiful Mind, A', 20.97, 33, 5);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('61*', 10.29, 30, 7);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Partners in Crime (Associés contre le crime...)', 18.58, 9, 13);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Guilty Hearts', 26.3, 46, 14);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Kronos', 22.85, 35, 10);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Perfectly Normal', 27.16, 38, 11);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('The Time Being', 8.96, 26, 4);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Workingman''s Death', 18.05, 7, 6);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Angels Sing', 15.87, 15, 3);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Blood and Concrete (Blood & Concrete: A Love Story)', 7.96, 21, 1);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Joe Versus the Volcano', 10.27, 17, 4);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Insider, The', 20.47, 10, 1);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Foo Fighters: Back and Forth', 12.57, 50, 11);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Wanderers', 21.16, 8, 13);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Honey, I Shrunk the Kids', 12.86, 39, 10);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Monica Z', 17.29, 2, 10);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Trust', 14.75, 24, 6);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Calcium Kid, The', 7.68, 10, 9);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Inspector Bellamy (Bellamy)', 12.37, 8, 6);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Sugar & Spice', 25.65, 49, 2);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Hart''s War', 12.58, 1, 4);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Way Back, The', 14.82, 22, 11);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Black Windmill, The', 25.41, 42, 12);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('I, Cesar (Moi César, 10 ans 1/2, 1m39)', 19.09, 11, 5);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Wicked Lady, The', 18.86, 20, 12);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Dead Birds', 28.16, 18, 9);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Jazz', 22.88, 16, 13);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Return of Frank James, The', 24.05, 44, 4);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Fade To Black', 27.76, 37, 1);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Ménage (Tenue de soirée)', 22.85, 12, 6);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Lucie Aubrac', 24.68, 13, 13);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Annie Get Your Gun', 16.0, 40, 14);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Day Is Done', 22.37, 21, 2);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('It Happened to Jane', 9.15, 46, 9);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('16 to Life', 12.59, 6, 2);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Package, The', 11.99, 33, 2);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Into the White (Cross of Honour)', 7.29, 28, 14);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Man on a Mission: Richard Garriott''s Road to the Stars', 28.68, 7, 2);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Mr. Popper''s Penguins', 29.9, 7, 2);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Perfect Murder, The', 8.96, 10, 7);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Trading Places', 22.94, 49, 14);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Bulworth', 18.21, 3, 14);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Leave', 22.87, 7, 3);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Good Mother, The', 28.38, 39, 10);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Story of Three Loves, The', 18.97, 43, 14);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Amazon Jack 2: The Movie Star (a.k.a. Hugo the Movie Star) (Jungledyret 2 - den store filmhelt)', 18.47, 28, 1);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Dans la peau d''une grande', 25.77, 11, 2);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Otaku', 5.19, 23, 13);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Girls, Les', 25.01, 33, 4);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Murder Most Foul', 24.97, 50, 12);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('For the Boys', 28.69, 13, 12);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Gasland Part II', 19.58, 43, 3);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Brotherhood of Death', 17.3, 4, 11);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Wisconsin Death Trip', 28.3, 46, 13);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Fire Birds', 12.81, 25, 1);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('And So It Goes', 13.44, 7, 7);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Midnight in Paris', 12.42, 31, 4);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Spirited Away (Sen to Chihiro no kamikakushi)', 22.91, 40, 2);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Fightville', 16.78, 3, 12);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Without Warning', 17.37, 22, 5);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Notti bianche, Le (White Nights)', 26.67, 5, 13);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Ed', 15.63, 12, 12);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Bread and Chocolate (Pane e cioccolata)', 5.17, 15, 1);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Unsaid, The', 19.77, 24, 13);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Pekka ja Pätkä salapoliiseina', 16.59, 42, 13);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Odgrobadogroba', 27.0, 29, 13);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Last Castle, The', 14.75, 28, 14);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Browning Version, The', 22.14, 32, 6);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Here Comes the Devil (Ahí va el diablo)', 5.82, 15, 1);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Miracle at Oxford (True Blue)', 29.07, 34, 9);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Riding the Bullet', 25.53, 46, 6);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('''Human'' Factor, The (Human Factor, The)', 20.27, 46, 10);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('White Dog', 18.73, 21, 14);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('This Film Is Not Yet Rated', 26.01, 50, 6);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Master and Margaret, The (Il maestro e Margherita)', 28.79, 41, 4);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Jessabelle', 25.97, 37, 2);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Midway', 9.2, 41, 10);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Conflagration (Enjô)', 24.6, 44, 10);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('From Zero to Hero', 8.33, 26, 13);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Leaning Tower, The (Kalteva torni)', 9.44, 49, 2);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Titanica', 17.85, 49, 2);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Tron', 20.96, 18, 5);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Cargo 200 (Gruz 200)', 10.15, 35, 4);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Elle: A Modern Cinderella Tale', 10.53, 2, 6);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Forgiven', 7.4, 4, 12);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Diminished Capacity', 14.98, 15, 6);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Lowlands (Tiefland)', 21.15, 27, 14);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Man in the Gray Flannel Suit, The', 22.42, 39, 12);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Billy Two Hats (Lady and the Outlaw, The)', 18.55, 18, 1);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('State Fair', 24.45, 45, 4);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Fishtales', 23.71, 47, 13);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('King of the Hill', 9.3, 37, 11);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Funny Lady', 17.75, 23, 3);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('The Princess Comes Across', 5.57, 30, 11);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Gigi', 13.42, 38, 8);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('To Have, or Not (En avoir (ou pas))', 29.9, 50, 7);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Mid-August Lunch (Pranzo di ferragosto)', 26.27, 9, 4);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Slackers', 16.32, 46, 2);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('How to Deal', 22.19, 5, 11);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Phantoms', 20.78, 27, 6);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('River Murders, The', 19.69, 7, 13);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Underground', 20.01, 48, 5);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Flirtation Walk', 22.96, 32, 14);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('One True Thing', 14.88, 38, 6);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Gone to Earth', 6.45, 5, 10);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Moon Child', 14.95, 7, 3);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('The Seven Males', 29.55, 44, 2);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Stir Crazy', 18.47, 42, 12);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Iceman', 20.9, 17, 12);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('3 Bad Men', 28.94, 24, 8);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Eden Is West (Eden à l''Ouest)', 23.2, 26, 3);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Orders to Kill', 24.9, 49, 6);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('To.get.her', 25.45, 3, 7);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Still Life (Sanxia haoren)', 9.71, 47, 12);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Waitress', 25.53, 4, 4);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('I Now Pronounce You Chuck and Larry', 12.69, 50, 10);
insert into piatto (nome, prezzo, ristorante_id, categoria_id) values ('Class of Nuke ''Em High Part II: Subhumanoid Meltdown', 27.14, 27, 10);
